spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin
logging:
  level:
    root: info
    com.chen: debug
  file:
    name: log/blog-dev.log
server:
  port: 8081