spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    show-sql: true
logging:
  level:
    root: warn
    com.chen: info
  file:
    name: log/blog-pro.log
server:
  port: 8085